version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "movies_database"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "123qwe"
    expose:
      - "5432"
    networks:
      - app_network

  migration:
    build: ./app
    image: movies_image
    command: python manage.py migrate --noinput
    volumes:
      - migration_volume:/opt/app/migrations
    depends_on:
      - postgres
    networks:
      - app_network

  web:
    image: movies_image
    depends_on:
      - postgres
      - migration
    env_file:
      - ./app/config/.env
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:/app/static
    depends_on:
      - web
    networks:
      - app_network

#  swagger:
#    image: swaggerapi/swagger-ui
#    container_name: swagger_ui_container
#    volumes:
#      - ./api_docs:/usr/share/nginx/html/doc
#    environment:
#      API_URL: doc/openapi.yaml
#    depends_on:
#      - nginx
#    ports:
#      - "8080:8080"
#    networks:
#      - app_network

volumes:
  postgres_data:
  static_volume:
  migration_volume:
networks:
  app_network:
